# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: TheRandomMelon's blog
email: trm@melonz.nl
description: TheRandomMelon's official Jekyll blog. I ramble about whatever I want, mainly memes and tech. I like memes and coding.
baseurl: ""
url: https://blog.trm.ovh
urlnp: blog.trm.ovh
twitter: https://twitter.com/RandomMelonYT
github: https://github.com/TheRandomMelon/therandommelon.github.io
permalink: /:year/:title.html

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
